let name = {
  config: {
    action: 'random'
  },
  data: [
    {"value": "Nick", "gender": "male"},
    {"value": "Ted", "gender": "male"},
    {"value": "Peter", "gender": "male"},
    {"value": "Alexander", "gender": "male"},
    {"value": "Nicholas", "gender": "male"},   
    {"value": "Ryan", "gender": "male"},
    {"value": "Ivan", "gender": "male"},
    {"value": "Lorenzo", "gender": "male"},
    {"value": "Ed", "gender": "male"},
    {"value": "Sam", "gender": "male"},
    {"value": "Andrew", "gender": "male"},
    {"value": "John", "gender": "male"},
    {"value": "James", "gender": "male"},
    {"value": "Jack", "gender": "male"},
    {"value": "Alex", "gender": "male"},
    {"value": "Carlos", "gender": "male"},
    {"value": "Adrian", "gender": "male"},
    {"value": "Jeremy", "gender": "male"},
    {"value": "Randy", "gender": "male"},
    {"value": "Arthur", "gender": "male"},
    {"value": "Orlando", "gender": "male"},
    {"value": "Joshua", "gender": "male"},
    {"value": "Mildred", "gender": "male"},
    {"value": "William", "gender": "male"},
    {"value": "Jacob", "gender": "male"},
    {"value": "Christopher", "gender": "male"},
    {"value": "Michael", "gender": "male"},
    {"value": "Anthony", "gender": "male"},
    {"value": "David", "gender": "male"},
    {"value": "Ethan", "gender": "male"},
    {"value": "Jayden", "gender": "male"},
    {"value": "Daniel", "gender": "male"},
    {"value": "Matthew", "gender": "male"},
    {"value": "Samuel", "gender": "male"},
    {"value": "Logan", "gender": "male"},
    {"value": "Wyatt", "gender": "male"},
    {"value": "Gavin", "gender": "male"},
    {"value": "Carter", "gender": "male"},
    {"value": "Noah", "gender": "male"},
    {"value": "Luis", "gender": "male"},
    {"value": "Jose", "gender": "male"},
    {"value": "Sophia", "gender": "female"},
    {"value": "Emma", "gender": "female"},
    {"value": "Lily", "gender": "female"},
    {"value": "Mia", "gender": "female"},
    {"value": "Olivia", "gender": "female"},
    {"value": "Katie", "gender": "female"},
    {"value": "Paula", "gender": "female"},
    {"value": "Madison", "gender": "female"},
    {"value": "Addison", "gender": "female"},
    {"value": "Ava", "gender": "female"},
    {"value": "Emily", "gender": "female"},
    {"value": "Chloe", "gender": "female"},
    {"value": "Anna", "gender": "female"},
    {"value": "Isabella", "gender": "female"},
    {"value": "Elizabeth", "gender": "female"},
    {"value": "Katherine", "gender": "female"},
    {"value": "Alexis", "gender": "female"},
    {"value": "Taylor", "gender": "female"},
    {"value": "Grace", "gender": "female"},
    {"value": "Nevaeh", "gender": "female"},
    {"value": "Ella", "gender": "female"},
    {"value": "Paola", "gender": "female"},
    {"value": "Abigail", "gender": "female"}
  ]
};

export default name;